// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanService 是暴露给前端的服务：局域网设备列表与信令中继。
 * 事件（前端用 @wailsio/runtime 的 Events.On 监听）：
 *   lan:peers    设备列表变化，data: lan.Peer[]
 *   lan:incoming 来电，data: {from, name, callId, sdp}
 *   lan:answer   呼叫被接听，data: {callId, sdp}
 *   lan:decline  呼叫被拒绝，data: {callId}
 *   lan:bye      对方挂断，data: {callId}
 *   lan:timeout  呼叫无应答超时，data: {callId}
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lan$0 from "./internal/lan/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptCall 接听来电（发送 WebRTC answer SDP）。
 * @param {string} peerID
 * @param {string} callID
 * @param {string} sdp
 * @returns {$CancellablePromise<void>}
 */
export function AcceptCall(peerID, callID, sdp) {
    return $Call.ByID(1145993450, peerID, callID, sdp);
}

/**
 * ClearDiagnostics 清空本机诊断日志。
 * @returns {$CancellablePromise<void>}
 */
export function ClearDiagnostics() {
    return $Call.ByID(1452950221);
}

/**
 * ConnectIP 主动向指定 IPv4 发起发现（广播被 AP 隔离/跨网段时的兜底）。
 * @param {string} ip
 * @returns {$CancellablePromise<void>}
 */
export function ConnectIP(ip) {
    return $Call.ByID(3782236549, ip);
}

/**
 * DeclineCall 拒绝来电。
 * @param {string} peerID
 * @param {string} callID
 * @returns {$CancellablePromise<void>}
 */
export function DeclineCall(peerID, callID) {
    return $Call.ByID(202617684, peerID, callID);
}

/**
 * Info 返回本机设备信息（前端用于展示与 IP 直连提示）。
 * @returns {$CancellablePromise<$models.DeviceInfo>}
 */
export function Info() {
    return $Call.ByID(1125987846).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LogDiagnostic 接收前端阶段日志；调用方不得传入完整 SDP、邀请码或媒体内容。
 * @param {string} level
 * @param {string} event
 * @param {string} detail
 * @returns {$CancellablePromise<void>}
 */
export function LogDiagnostic(level, event, detail) {
    return $Call.ByID(3859594371, level, event, detail);
}

/**
 * Peers 返回当前在线的局域网设备。
 * @returns {$CancellablePromise<lan$0.Peer[]>}
 */
export function Peers() {
    return $Call.ByID(3829660335).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ReadDiagnostics 返回最近的诊断日志，供前端导出。
 * @returns {$CancellablePromise<string>}
 */
export function ReadDiagnostics() {
    return $Call.ByID(3216835558);
}

/**
 * SendBye 通知对方结束通话。
 * @param {string} peerID
 * @param {string} callID
 * @returns {$CancellablePromise<void>}
 */
export function SendBye(peerID, callID) {
    return $Call.ByID(2730848164, peerID, callID);
}

/**
 * SendOffer 向指定设备发起呼叫（发送 WebRTC offer SDP）。
 * @param {string} peerID
 * @param {string} callID
 * @param {string} sdp
 * @returns {$CancellablePromise<void>}
 */
export function SendOffer(peerID, callID, sdp) {
    return $Call.ByID(3609637546, peerID, callID, sdp);
}

/**
 * SetBusy 更新本机占线状态，随 announce 广播给局域网内设备。
 * @param {boolean} busy
 * @returns {$CancellablePromise<void>}
 */
export function SetBusy(busy) {
    return $Call.ByID(484288619, busy);
}

/**
 * SetName 修改本机设备名并持久化。
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetName(name) {
    return $Call.ByID(786929261, name);
}

// Private type creation functions
const $$createType0 = $models.DeviceInfo.createFrom;
const $$createType1 = lan$0.Peer.createFrom;
const $$createType2 = $Create.Array($$createType1);
